server:
  port: 8081
swagger:
  title: spring-boot-starter-swagger
  description: Starter for swagger 2.x
  version: 1.4.0.RELEASE
  license: Apache License, Version 2.0
  license-url: https://www.apache.org/licenses/LICENSE-2.0.html
  terms-of-service-url: https://github.com/dyc87112/spring-boot-starter-swagger
  base-package: com.xasmall.lab4
  base-path: /**
  contact:
    name: xasmall
    url: xxxx.com
    email: xxxx@cc.com
