# ?????
book:
  name: SpringBoot
  author: Spring???
#  ??${}????????????
  desc: ${book.author} is writting ?${book.name}?
  value: ${random.int}
  bigNumber: ${random.long}

# ?????????????????
spring:
  profiles:
    active: dev
